# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iOS Ref
description: Quick reference tables, tools, and links for iOS developers. iOS Ref has iOS compatibility tables, a beautiful Swift cheatsheet, a hex code to UIColor converter, device screen resolution tables, and more.
author: Eugene Belinski
keywords: iOS,reference,ref,watchOS,Xcode,tool,hex,uicolor,swift,cheatsheet

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-redirect-from

collections:
  subpages:
    output: true
    permalink: /:name

sass:
  quiet_deps: true